name: Build and Deploy Code

on: [push, pull_request]
    # push:
    #     branches:
    #         - "main"
    # pull_request:
    #     branches:
    #         - "test_branch"

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: pulling git repo
              uses: actions/checkout@v4
            - name: say hi to bebo
              run: echo "Hello Bebo"